language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

addons:
  sauce_connect: true

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: G3XxsVV6gAkHCJu1kfoQnSzFSP5Hsw4gKmyjFLzmRMEECCZsao1L+9n1Olk5gc23glMqIoJN4w2s58RkLPh0e9XtpNcKbSRw87dkMYpxIATetjpI18g5e7rED+RvBq/w/jBNnjqm3tetrkDSDmdWs3oMjUuI9lCj3tiV82ZMu2s=
  app: upload-button
  on:
    repo: Wildhoney/UploadButton

env:
  global:
    - secure: Rkd83oa0vufVT+EisAYnRcXJcCVfwnLPn2VZC5LDstktMbe3fxhBWnS0FtWcR+DPUD9Y3D83jLp9UVqsB7JNACXMa2YOupYpo3QW3ogtf2W4pXvr2uULp9WNgaj5zIjFK8sb7o7M7PU5FcguwvbqWIkz+Ttu1Pg4r9dmA1KXqTU=
    - secure: DeaXbbZoQo4d420PMypzYqu1jrmNjsrq/04wq14vfaJRmoJ2q+kGXb5KqqxMSrtZQsods5lF/vEvM28zaRND7nABt9gv837RqZh5AvuDTZhKbJleEow5Nf+O6oeg9SLvK5Ti2rqF/b6SNZbFqEVvzC35cw9Ty1No2Benz+U3O80=