language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

addons:
  sauce_connect: false

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: G3XxsVV6gAkHCJu1kfoQnSzFSP5Hsw4gKmyjFLzmRMEECCZsao1L+9n1Olk5gc23glMqIoJN4w2s58RkLPh0e9XtpNcKbSRw87dkMYpxIATetjpI18g5e7rED+RvBq/w/jBNnjqm3tetrkDSDmdWs3oMjUuI9lCj3tiV82ZMu2s=
  app: upload-button
  on:
    repo: Wildhoney/UploadButton

env:
  global:
    - secure: YqIcgalbfRcH6fioiVx+6uBsFWTw8vLZkGC08EOOX66iZRHMz4ChVQklj6dF3KDI5WV60UGqiOBFAVc2XEPIo3LkfGgdRU0Tgn/JWT8YLk9QQoQyiuRcLG8z8PKmtvjmG3huhyaEz0dfgHsDp95QEaSabRylSj3GIkFYPNOHspk=
    - secure: D5KyrOgcV4A6GchgKv1M+te1SxhfrfijmbavUh5rG9360vcP5RiXNF9ic4Ho9lD1pzX0gJG3SApt0xk+ogbbhR1D/6RwDD/6Tnqd9d7vrsxe7rg+5LbYruCQ74QVScA7sk6QZgSAkyYWBV8kJB8ez+mYnaNeuDeSZ+Nywc/c750=