language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - bower install
  - gulp test
  - gulp build

addons:
  sauce_connect: true

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: G3XxsVV6gAkHCJu1kfoQnSzFSP5Hsw4gKmyjFLzmRMEECCZsao1L+9n1Olk5gc23glMqIoJN4w2s58RkLPh0e9XtpNcKbSRw87dkMYpxIATetjpI18g5e7rED+RvBq/w/jBNnjqm3tetrkDSDmdWs3oMjUuI9lCj3tiV82ZMu2s=
  app: upload-button
  on:
    repo: Wildhoney/UploadButton

env:
  global:
  - secure: P36W/MYFAcjkpT6LGjwJbzYynlc2ROgl4FUt/VYo8OijXWy4Ar3/YgDA/0Etp0Nl6Q05HAkIZyRbVZdGj+XYalf38wPSLkmIHgfFu8YzmunDkMhBtmsDsdNE4JPawW+NMVgyBWFMYPkYiyUQ+gCF6nmibqKQTDyi04+CpJWFVkk=
  - secure: hlvQm1mKita0lk+f8nse1mXEIfaJWR/uLhySRYYfA9gfUmqIOwaRIzobzaOUDcxU+QPLPGQIxo8+xc2cEr1RSHPs3jEDgPDj3aBbSCIu1AKd64lokMdUscVKLlHnR7LIQDULm7BPacUZPRy6Q1OaCiAkdimYPstmVxttHLWhZ/o=