language: node_js

node_js:
  - '0.10'
  - '0.11'

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

addons:
  sauce_connect:
    username: Wildhoney
    access_key:
      secure: hAqxxJHOdW7Y5IOSPEMDrkHNsjDWIwvlRR2CMqL/EB/xUqUyeadDRz8UHgx93HDaArylXqaYtufivMg3bH+NNc2Hpn0gFDAWc1o6/qUXdC7Qb5nBvRqMNnIaDkYEL6JuutjusTtA6DCKnaDTXkmgzqQJY5/8PX7y1n3YgCd9Le8=

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: G3XxsVV6gAkHCJu1kfoQnSzFSP5Hsw4gKmyjFLzmRMEECCZsao1L+9n1Olk5gc23glMqIoJN4w2s58RkLPh0e9XtpNcKbSRw87dkMYpxIATetjpI18g5e7rED+RvBq/w/jBNnjqm3tetrkDSDmdWs3oMjUuI9lCj3tiV82ZMu2s=
  app: upload-button
  on:
    repo: Wildhoney/UploadButton